name: Flutter CI/CD

on:
  push:
    branches:
      - main # Hoặc nhánh chính của bạn

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17' # Flutter yêu cầu Java 17 cho Android build

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Sử dụng kênh stable của Flutter

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Analyze Flutter code
        run: flutter analyze

      - name: Run Flutter tests
        run: flutter test

      - name: Build Android APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk